// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';
import keycloakConfig from './keycloak.config';

export const environment = {
  production: false,
  keycloak: keycloakConfig,
  version: env['npm_package_version'] + '-dev',
  //serverUrl - Data Science API
  serverUrl: '',
  //diyDataServiceUrl is used for Enhance prompts, group details and chat history
  diyDataServiceUrl: '',
  //networkQuestionsUrl - DS API
  networkQuestionsUrl: '',
  // Used in i18n for language detection and text translation
  telemetryUrl: '',
  whisperApiKey: '',
  whisperApiUrl: '',
  defaultGroup: 'Public',
  defaultLanguage: 'English',
  supportedLanguages: [
    'English',
    'Deutsch',
    'Española',
    'Français',
    'Português',
    'हिंदी',
    'ಕನ್ನಡ',
    'தமிழ்',
    'मराठी'
  ],
  orgLanguages: {
    'Group 1': ['Deutsch', 'Española', 'Français', 'Português'],
    TNKoboTool: ['Deutsch', 'Española', 'Français', 'Português', 'हिंदी', 'ಕನ್ನಡ', 'தமிழ்', 'मराठी'],
  },
  defaultPreviewImage: '/assets/Apurva-logo-final.png',
};
